# Pandas

## Introduction

### What is Pandas?

For more information, check out the [Pandas Documentation](https://pandas.pydata.org/).

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.
When working with tabular data, such as data stored in spreadsheets or databases, pandas will help you to explore, clean, and process your data.

### Installing Pandas

To install pandas using pip, simply run:

```bash
pip install pandas
```

### Importing Pandas

The standard convention is to import pandas under the `pd` alias.

In [1]:
import pandas as pd

## Basics

### Basic Data Structures

Pandas provides two types of classes for handling data:

- `Series`: a one-dimensional labeled array holding data of any type such as integers, strings, Python objects etc. It resembles a column in a spreadsheet.

- `DataFrame`: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

In [2]:
scores = pd.Series([85, 92, 78, 95, 88]) # Pandas Series
print(scores)

0    85
1    92
2    78
3    95
4    88
dtype: int64

In [3]:
employees = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hilda"],
    "department": ["Engineering", "Marketing", "Engineering", "HR", "Marketing", "Engineering", "Marketing", "Marketing"],
    "salary": [90000, 72000, 85000, 65000, 78000, 95000, 82000, 75000],
    "years": [5, 3, 7, 2, 4, 8, 6, 5],
    "rating": ["4.5", "3.8", "4.2", "3.5", "4.0", "4.7", "4.1", "3.9"],
    "join_date": ["2019-03-15", "2021-07-01", "2017-11-20", "2022-01-10", "2020-05-05", "2016-09-30", "2018-12-15", "2021-11-20"]
}

df = pd.DataFrame(employees)

print(df)

      name   department  salary  years rating   join_date
0    Alice  Engineering   90000      5    4.5  2019-03-15
1      Bob    Marketing   72000      3    3.8  2021-07-01
2  Charlie  Engineering   85000      7    4.2  2017-11-20
3    David           HR   65000      2    3.5  2022-01-10
4      Eve    Marketing   78000      4    4.0  2020-05-05
5    Frank  Engineering   95000      8    4.7  2016-09-30
6    Grace    Marketing   82000      6    4.1  2018-12-15
7    Hilda    Marketing   75000      5    3.9  2021-11-20

### Loading and Saving Data

Pandas supports the integration with many file formats or data sources out of the box such as csv, excel, sql, json, parquet e.t.c. We are able to read and save to these file formats.

In [4]:
# Saving
df.to_csv("employees.csv", index=False) # `index=False` avoids a redundant row-number column
df.to_json("employees.json", orient="records")
df.to_excel("employees.xlsx", index=False)

In [5]:
# Loading
df_csv = pd.read_csv("employees.csv")
df_json = pd.read_json("employees.json")
df_excel = pd.read_excel("employees.xlsx")

print("\nDataframe from CSV")
print(df_csv)
print("\nDataframe from JSON")
print(df_json)
print("\nDataframe from Excel")
print(df_excel)

Dataframe from CSV
      name   department  salary  years  rating   join_date
0    Alice  Engineering   90000      5     4.5  2019-03-15
1      Bob    Marketing   72000      3     3.8  2021-07-01
2  Charlie  Engineering   85000      7     4.2  2017-11-20
3    David           HR   65000      2     3.5  2022-01-10
4      Eve    Marketing   78000      4     4.0  2020-05-05
5    Frank  Engineering   95000      8     4.7  2016-09-30
6    Grace    Marketing   82000      6     4.1  2018-12-15
7    Hilda    Marketing   75000      5     3.9  2021-11-20

Dataframe from JSON
      name   department  salary  years  rating   join_date
0    Alice  Engineering   90000      5     4.5  2019-03-15
1      Bob    Marketing   72000      3     3.8  2021-07-01
2  Charlie  Engineering   85000      7     4.2  2017-11-20
3    David           HR   65000      2     3.5  2022-01-10
4      Eve    Marketing   78000      4     4.0  2020-05-05
5    Frank  Engineering   95000      8     4.7  2016-09-30
6    Grace    Marketing   82000      6     4.1  2018-12-15
7    Hilda    Marketing   75000      5     3.9  2021-11-20

Dataframe from Excel
      name   department  salary  years  rating   join_date
0    Alice  Engineering   90000      5     4.5  2019-03-15
1      Bob    Marketing   72000      3     3.8  2021-07-01
2  Charlie  Engineering   85000      7     4.2  2017-11-20
3    David           HR   65000      2     3.5  2022-01-10
4      Eve    Marketing   78000      4     4.0  2020-05-05
5    Frank  Engineering   95000      8     4.7  2016-09-30
6    Grace    Marketing   82000      6     4.1  2018-12-15
7    Hilda    Marketing   75000      5     3.9  2021-11-20

## Viewing and Inspecting our Data

### Viewing Data

To take a sneak peek at your data, you can use three methods: `head()`, `tail()` and `sample()`.

`head(n)` returns the first `n` rows. Likewise, `tail(n)` returns the last `n` rows. On the other hand, `.sample(n)` returns `n` randomly selected rows.

In [6]:
df.head() # default: 5

      name   department  salary  years rating   join_date
0    Alice  Engineering   90000      5    4.5  2019-03-15
1      Bob    Marketing   72000      3    3.8  2021-07-01
2  Charlie  Engineering   85000      7    4.2  2017-11-20
3    David           HR   65000      2    3.5  2022-01-10
4      Eve    Marketing   78000      4    4.0  2020-05-05

In [7]:
df.tail() # default: 5

    name   department  salary  years rating   join_date
3  David           HR   65000      2    3.5  2022-01-10
4    Eve    Marketing   78000      4    4.0  2020-05-05
5  Frank  Engineering   95000      8    4.7  2016-09-30
6  Grace    Marketing   82000      6    4.1  2018-12-15
7  Hilda    Marketing   75000      5    3.9  2021-11-20

In [8]:
df.sample() # default: 1

    name department  salary  years rating   join_date
3  David         HR   65000      2    3.5  2022-01-10

In [9]:
df.head(3) # gets the first 3 elements instead

      name   department  salary  years rating   join_date
0    Alice  Engineering   90000      5    4.5  2019-03-15
1      Bob    Marketing   72000      3    3.8  2021-07-01
2  Charlie  Engineering   85000      7    4.2  2017-11-20

### Inspecting Data

There are also functions that help us examine our DataFrame in detail.

`info()` gives you a structural overview of the DataFrame. This includes the column names, how many non-null values each column has, and the data type of each column. It's usually the first thing you run on a new dataset because it immediately tells you if anything is missing and whether columns were loaded as the right data type.

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        8 non-null      str
 1   department  8 non-null      str
 2   salary      8 non-null      int64
 3   years       8 non-null      int64
 4   rating      8 non-null      str
 5   join_date   8 non-null      str
dtypes: int64(2), str(4)
memory usage: 516.0 bytes

`describe()` gives you summary statistics for every numeric columns and includes things like the mean, min, max, and percentiles (25%, 50%, 75%). The 50% row is just the median. This is great for spotting things like outliers (if the max is wildly far from the 75th percentile, something is off) or whether your data is skewed.

In [11]:
df.describe()

             salary  years
count      8.000000   8.00
mean   80250.000000   5.00
std     9794.313219   2.00
min    65000.000000   2.00
25%    74250.000000   3.75
50%    80000.000000   5.00
75%    86250.000000   6.25
max    95000.000000   8.00

`shape` returns a tuple of (number of rows, number of columns)

In [12]:
print(f"Shape: {df.shape}")

Shape: (8, 6)

`columns` lists all column names.

In [13]:
print(f"Columns: {df.columns.tolist()}")

Columns: ['name', 'department', 'salary', 'years', 'rating', 'join_date']

`index` shows the row labels.

In [14]:
print("Index:  ", df.index.tolist())

Index:   [0, 1, 2, 3, 4, 5, 6, 7]

In [15]:
print(f"Dtypes:\n{df.dtypes}")

Dtypes:
name            str
department      str
salary        int64
years         int64
rating          str
join_date       str
dtype: object

## Selection

### Selecting Columns

You can select a column with:

In [16]:
print(df.name)

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
7      Hilda
Name: name, dtype: str

However, if you want to access a column with a name that has spaces or special characters, you can use the bracket notation. This way is usually preferred.

In [17]:
# Single column
print(df["name"])

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
5      Frank
6      Grace
7      Hilda
Name: name, dtype: str

In [18]:
# Multiple Columns
print(df[["name", "salary", "department"]])

      name  salary   department
0    Alice   90000  Engineering
1      Bob   72000    Marketing
2  Charlie   85000  Engineering
3    David   65000           HR
4      Eve   78000    Marketing
5    Frank   95000  Engineering
6    Grace   82000    Marketing
7    Hilda   75000    Marketing

When you write `df["name"]`, you get back a Series. Think of it as pulling out a single column from the table. When you write `df[["name", "salary", "department"]]` (double brackets), you get back a DataFrame, which is just a mini-table with only those columns.

### Selecting Rows: `.loc` and `.iloc`

The difference is that `.loc` thinks in labels while `.iloc` thinks in positions. 

`.loc` uses the actual index label and column name, so `df.loc[2, "salary"]` means "row labelled 2, column named salary", and slicing with `df.loc[1:3]` is inclusive on both ends, giving you rows 1, 2, and 3. 

`.iloc` on the other hand uses integer positions like a list index, so `df.iloc[0, 2]` means "first row, third column" regardless of what the column is named, and `df.iloc[1:3]` follows normal Python slicing rules where the right end is exclusive, giving you only positions 1 and 2.

| Method | Uses | Example |
|--------|------|---------|
| `.loc` | **Label-based:** index labels and column names | `df.loc[0, "name"]` |
| `.iloc` | **Integer-based:** row/column position numbers | `df.iloc[0, 1]` |

In [19]:
print(df.loc[2])

name              Charlie
department    Engineering
salary              85000
years                   7
rating                4.2
join_date      2017-11-20
Name: 2, dtype: object

In [20]:
print(df.loc[0, "name"])

Alice

In [21]:
print(df.loc[1:3, ["name", "salary"]])

      name  salary
1      Bob   72000
2  Charlie   85000
3    David   65000

In [22]:
print(df.iloc[0, 1])

Engineering

In [23]:
print(df.iloc[0:3, 0:3])

      name   department  salary
0    Alice  Engineering   90000
1      Bob    Marketing   72000
2  Charlie  Engineering   85000

In [24]:
print(df.iloc[-1])

name               Hilda
department     Marketing
salary             75000
years                  5
rating               3.9
join_date     2021-11-20
Name: 7, dtype: object

## Converting Datatypes

In [25]:
print(df.dtypes)

name            str
department      str
salary        int64
years         int64
rating          str
join_date       str
dtype: object

### `astype()`

We can convert between datatypes using `astype()`. Take the `salary` column for example. Currently it is stored as `int6`4, but we can convert it to float.

In [26]:
df["salary"] = df["salary"].astype(float)

print(df["salary"].dtype)

float64

We will also convert the `department` column to the `category` type. This makes sense for columns that have a small number of repeating values (like "Engineering", "Marketing", "HR"). Storing them as category instead of plain strings uses less memory and can also make certain operations faster.

In [27]:
df["department"] = df["department"].astype("category")

print(df["department"].dtype)

category

### Converting from Strings to Numbers

When you read data from a CSV or Excel file, pandas sometimes loads number columns as strings, especially if the column had mixed content like `"42"`, `"N/A"`, or `"$100"`. Calling `astype(float)` on a column like that will crash immediately if it hits any value it cannot convert.

`pd.to_numeric()` is the safer alternative because it is specifically designed for converting to numbers and gives you control over what happens when it encounters a bad value through the errors parameter, which has three options:

- `errors="raise"`:the default, crashes on bad values just like `astype()`
- `errors="coerce"`: converts bad values to `NaN` instead of crashing, and carries on
- `errors="ignore"`: leaves bad values as they are and carries on

You may notice that our `rating` column is stored as a string. Since we want to perform numerical operations on it, let us convert it to a number.

In [28]:
print(df["rating"].dtype)

str

In [29]:
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

print(df["rating"].dtype)

float64

### Working with Datetime

Datetime is one of the most important types in data analysis because dates appear in almost every real dataset: order dates, sign-up times, transaction records and so on. The problem is that sometimes, when pandas loads a file, it may read date columns as plain strings, so you cannot do things like extract the month or calculate the gap between two dates. Fortunately, we can convert to datetime using `pd.to_datetime()`.

In [30]:
print(df["join_date"].dtype)

str

In [31]:
df["join_date"] = pd.to_datetime(df["join_date"], errors="coerce")

print(df["join_date"].dtype)
print(df["join_date"])

datetime64[us]
0   2019-03-15
1   2021-07-01
2   2017-11-20
3   2022-01-10
4   2020-05-05
5   2016-09-30
6   2018-12-15
7   2021-11-20
Name: join_date, dtype: datetime64[us]

In [32]:
# The .dt accessor gives you datetime components
print(df["join_date"].dt.year)

0    2019
1    2021
2    2017
3    2022
4    2020
5    2016
6    2018
7    2021
Name: join_date, dtype: int32

In [33]:
print(df["join_date"].dt.day_name())

0      Friday
1    Thursday
2      Monday
3      Monday
4     Tuesday
5      Friday
6    Saturday
7    Saturday
Name: join_date, dtype: str

## Data Transformation

Creating new columns
Mathematical operations
map(), apply()
sorting

## Grouping and Aggregation

- values_count()
- groupby()

- Aggregate functions
    - Mean
    - Sum
    - Count
    - Min and Max

- Sorting

## Conditional Filtering

- Boolean Indexing
- | &
- query()
- Multiple conditions
- filtering with .isnull and other methods

## Merge and Pivot

Reshaping Data

## Stacking functions together

i.e df.isna().sum()

Forget about Cleaning the data, duplicates and missing data. Thats another notebooks work.

## Assignment